### ISSUE TITLE
Extra Wound Dots

### ISSUE THREAD

**Issue by MushyRicey** [jdgwf/ffg-sw-genesys-helpers#7]
The first wound dots have 1 extra dot.

**Comment by jdgwf** [comment]
The functionality of how the wound dots work in Genesys and Star Wars has been decided in committee (Discord) on when wound thresholds have been exceeded. The current functionality is correct.

This is already a non-standard way of counting wounds as folks don't "count down to zero" in either system, they count up to wounds and if the wounds exceed the threshold the minion/rival/nemesis is out of action. The current wound dot method is about as accurate as one can get with a "Wound Track" system to how it plays in game.
