### ISSUE TITLE
Cunning and Smart Persons Stats for Cun and Int are reverse.

### ISSUE THREAD

**Issue by dlwest72** [jdgwf/ffg-sw-genesys-helpers#9]
- Cunning and Smart Persons Stats for Cun and Int are reverse.
- In the Adversary base list Cunning is high stat for Smart Person
- and Int is high stat for Cunning Foe

**Comment by jdgwf** [comment]
Fixed. Sorry about the wait.. didn't get email notifications and health issues (see personal blog if you're interested)

**Comment by dlwest72** [comment]
No worries. Thanks for the fix.
